canonical/kubeflow-volumes-operator

- .github/workflows/publish.yaml
Publishes to charmhub via charmcraft. Blocked on succeeding currently due to kubeflow-volumes being marked read-only on charmhub.io
> Fix publishing job

- .github/workflows/publish.yaml
This charm will act as a test charm for "split-brain" publishing, where we get to actually test out publishing to charmhub via charmcraft, but at the expense of also managing keeping the charm store in sync manually instead of relying on the background sync process.
> Reintroduce Charm Store publishing

- src/charm.py
- tests/integration/test_charm.py
fixes error where non-string input will cause an exception when instantiating the `status`
> fix: force CheckFailed msg arg to string, fix CI

- requirements.txt
Ops<1.2 could have the case where the charm asks for relation data before it was available, resulting in odd failures where relations are established but even the initial data posted to them is not available as expected.
> Bump ops to fix relation data race condition

- .github/workflows/integrate.yaml
- .github/workflows/on_pull_request.yaml
- .github/workflows/on_push.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
- src/charm.py
- test-requirements.txt
- tests/integration/test_charm.py
Charming actions updated according to the ones agreed on template-operator charm.
The aim was to:
- add release charm action
- have two publish actions for `on: push` and `on: pull_request`:
- on pull_request, publish to branch no matter if tests passed (tests and publish should run simultaneously)
- on push, publish to latest/edge only if tests passed
- avoid re-running the tests on pull_request
- use reusable workflows in order to avoid duplication of code.
Note: this is a single-charm repo with one resource.
> Add charming actions and unpin black version

- test-requirements.txt
- tox.ini
This fixes an issue found when previous PR was merged.  See [this CI run](https://github.com/canonical/kubeflow-volumes-operator/pull/32).  That issue was caused because this charm's CI has a pylibjuju dependency pinned to the [juju main branch](https://github.com/juju/python-libjuju) rather than a released package.  There was a change to the main branch sometime recently that breaks this charm (and also breaks [dex](https://github.com/canonical/dex-auth-operator/runs/7560442093?check_suite_focus=true#step:5:1924) and probably others).  Pinning to the released pypi version of Juju fixes the issue
When merging this PR, squash and merge to remove junk commits in the middle
> fix: integration.yaml CI failure

- src/charm.py
- tests/unit/test_operator.py
When we use `juju upgrade-charm`, a new non-leader unit gets created, then the old still-leader one gets removed, resulting in the new unit being elected as the leader.
When the `leader_elected` event is not observed, the charm is not aware of having a leader now, so it remains stuck with message 'Waiting for leadership'.
This PR adds a fix to observe this event.
> Observe leader-elected event

- tests/integration/profile.yaml
- tests/integration/test_charm.py
Removes the profile config option from the deployment of dashboard.  This option has been removed from the dashboard charm
> fix: remove deprecated dashboard config from tests

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
- test-requirements.txt
In track/1.6, this PR pins:
* `runs-on: ubuntu-latest` to avoid getting runners that cannot build our charms
* flake8<6 to mitigate an incompatibility between flake8 6 and the flake8-copyright plugin
> fix: pin ubuntu version, flake8 in track/1.6

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
- test-requirements.txt
In main, this PR pins:
* `runs-on: ubuntu-latest` to avoid getting runners that cannot build our charms
* flake8<6 to mitigate an incompatibility between flake8 6 and the flake8-copyright plugin
> fix: pin ubuntu version, flake8 in main 

- metadata.yaml
- tests/integration/test_charm.py
This vendors all remotely defined serialized-data-interface schemas, embedding them in the respective metadata.yaml(s) rather than storing them as a remote link.  This is to enable offline deployment of the charms, as described in [jira](https://warthogs.atlassian.net/browse/KF-727?atlOrigin=eyJpIjoiN2JjZTdlMGYxNDQ3NDdlYzljZDQxNDQ1MTk0OTdkNTEiLCJwIjoiaiJ9).
> feat: localize SDI schemas

- lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
- lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_sidebar.py
- metadata.yaml
- src/charm.py
Adds the sidebar relation for kubeflow-dashboard, plus the library to manage it.  This allows this charm to request a link in the kubeflow dashboard's sidebar.
> feat: add kubeflow-dashboard sidebar relation

- requirements-unit.in
- requirements-unit.txt
Remove bcrypt package from unit test dependencies.
NOTE: bcrypt is still indirect requirement for juju in integration tests 
Closes https://github.com/canonical/kubeflow-volumes-operator/issues/99
> Remove bcrypt from unittests

- .github/workflows/integrate.yaml
- requirements-integration.in
- requirements-integration.txt
- tests/integration/test_charm.py
- ci: update juju to 3.1 and microk8s to 1.25
- remove `wait_for_units` parameter from the `wait_for_idle` call, due to it being deprecated in pyjuju 3, the method is now set to `wait_for_units` by default when `wait_for_at_least_units` is not set so there's no change in the behavior of the test
> ci: update juju to 3.1 and microk8s to 1.25

- config.yaml
This PR integrates the rock built from https://github.com/canonical/filebrowser-rock.
Contributes to #126 
note:
* this PR will not be properly tested by the current charm integration tests.  we need to do additional manual testing to assert this worked
* at time of writing, to test the volumes webapp UI you need to deploy the full kubeflow bundle as we have not defined a minimum bundle that makes volumes function properly. Deploying what the integration CI deploys here is not enough
```
juju deploy kubeflow --channel 1.8/stable --trust
juju scale-application kubeflow-volumes 0
sleep 10
juju refresh kubeflow-volumes --channel latest/edge/pr-127
juju trust kubeflow-volumes --scope=cluster
juju scale-application kubeflow-volumes 1
juju config dex-auth static-username=user123
juju config …
```
> Integrate the filebrowser rock into `main`

- config.yaml
change the filebrowser default image to use our rock from https://github.com/canonical/filebrowser-rock
closes #126 
See #126
> Integrate the filebrowser rock into `track/1.8`

- tests/integration/test_charm.py
The integration tests were deploying versions of dependency charms that do not correspond to the current release of this charm(s). This commit brings all the correct versions and configure charms accordingly to ensure the integration tests execute in the same environment as this version of the charm(s) was design for.
> tests: point all the integration charm deps to their 1.8 versions

- .github/workflows/integrate.yaml
- requirements-integration.txt
- requirements-unit.in
- requirements-unit.txt
- requirements.txt
Bumping juju and ops packages to use them in newer versions of the charms, plus testing them in a CI with a more recent juju version.
Part of canonical/bundle-kubeflow#859
Merge after #131
> build: bump juju, ops versions in ci and requirements files

- config.yaml
- metadata.yaml
Closes: https://github.com/canonical/kubeflow-volumes-operator/issues/134
I have compared tags `v1.8.0` and `v1.9.0-rc.0` for these files: https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/volumes
Changes 
- image + filebrowser image
**Note:** Ignoring filebrowser as we already support higher ROCK version
> Update kubeflow-volumes-operator to 2.2.0

- lib/charms/loki_k8s/v1/loki_push_api.py
- metadata.yaml
- requirements-integration.in
- requirements-integration.txt
- requirements-unit.txt
- requirements.in
- requirements.txt
- src/charm.py
- tests/integration/test_charm.py
- tests/unit/test_operator.py
Use LogForwarder from loki_push_api library to forwards all logs from workload container to Loki. This requires to use ops 2.9 or newer, so it was needed to be updated.
fixes: #136
How I tested it:
```bash
$ tox -e integration -- --keep-models
$ juju switch test-charm-aosq
$ juju consume u1-k8s:cos.loki-logging 
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate grafana-agent-k8s loki-logging
$ kubectl get services -n test-charm-aosq | grep kubeflow-volumes
kubeflow-volumes-endpoints       ClusterIP      None             <none>        <none>                                  90m
kubeflow-volumes                 ClusterIP      10.152.183.49    <none>        5000/TCP                                90m 
$ curl 10.152.183.49:5000
...
```
And after checking the Grafana, I was …
> Add logging relation to kubeflow-volumes

- metadata.yaml
Closes #143 
Compared tags v1.9.0-rc.0 and v1.9.0 after generating manifests with:
```
kustomize build apps/volumes-web-app/upstream/overlays/istio > volumes-v1.9.0-rc-0.yaml
kustomize build apps/volumes-web-app/upstream/overlays/istio > volumes-v1.9.0.yaml
diff volumes-v1.9.0-rc-0.yaml volumes-v1.9.0.yaml > volumes-v1.9.0-rc.0-v1.9.0.diff
```
Changes in `viewer-spec.yaml` were already here for us (not sure why).
> chore: bump image to 1.9.0

- lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
part of fixing https://github.com/canonical/kubeflow-dashboard-operator/issues/213
bumps the `KubeflowDashboardLinks` lib to Patch 3, lib was updated in https://github.com/canonical/kubeflow-dashboard-operator/pull/219
> chore: bump dashboard links lib

- metadata.yaml
- src/components/pebble_components.py
Closes: https://github.com/canonical/kubeflow-volumes-operator/issues/153
After this we need to backport this changes to track branch for 1.9.
> Use 1.9.0 rock

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
- metadata.yaml
Upgrade image according to KF/KF 1.10.0-rc.0 and KF/manifests v1.10.0-rc.1.
Whole manifests diff.
```diff
165a166
>   VWA_APP_ENABLE_METRICS: "1"
176c177
<   name: volumes-web-app-parameters-57h65c44mg
---
>   name: volumes-web-app-parameters-mbftc78hbk
288c289,291
<         image: docker.io/kubeflownotebookswg/volumes-web-app:v1.9.2
---
>         - name: METRICS
>           value: "1"
>         image: docker.io/kubeflownotebookswg/volumes-web-app:v1.10.0-rc.0
```
This is pointed to a dev branch and metrics feature + tests is introduced in a follow-up PR.
Ref https://warthogs.atlassian.net/browse/KF-6867
> chore: upgrade manifests to 1.10.0-rc.0

- metadata.yaml
Closes https://warthogs.atlassian.net/browse/KF-7149
The only changes introduced in Kubeflow 1.10.0-rc.3 were image updates, thus we just need to integrate the rocks for version 1.10.0 of the volumes web app according to https://github.com/kubeflow/manifests/pull/3071.
> chore: integrate volumes rock 1.10.0
